/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LangRouteRouteImport } from "./routes/$lang/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as LangIndexRouteImport } from "./routes/$lang/index"
import { Route as LangTeamRouteImport } from "./routes/$lang/team"
import { Route as LangPricingRouteImport } from "./routes/$lang/pricing"
import { Route as LangBlogRouteImport } from "./routes/$lang/blog"

const LangRouteRoute = LangRouteRouteImport.update({
  id: "/$lang",
  path: "/$lang",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTeamRoute = LangTeamRouteImport.update({
  id: "/team",
  path: "/team",
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPricingRoute = LangPricingRouteImport.update({
  id: "/pricing",
  path: "/pricing",
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogRoute = LangBlogRouteImport.update({
  id: "/blog",
  path: "/blog",
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/$lang": typeof LangRouteRouteWithChildren
  "/$lang/blog": typeof LangBlogRoute
  "/$lang/pricing": typeof LangPricingRoute
  "/$lang/team": typeof LangTeamRoute
  "/$lang/": typeof LangIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/$lang/blog": typeof LangBlogRoute
  "/$lang/pricing": typeof LangPricingRoute
  "/$lang/team": typeof LangTeamRoute
  "/$lang": typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/$lang": typeof LangRouteRouteWithChildren
  "/$lang/blog": typeof LangBlogRoute
  "/$lang/pricing": typeof LangPricingRoute
  "/$lang/team": typeof LangTeamRoute
  "/$lang/": typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/$lang"
    | "/$lang/blog"
    | "/$lang/pricing"
    | "/$lang/team"
    | "/$lang/"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/$lang/blog" | "/$lang/pricing" | "/$lang/team" | "/$lang"
  id:
    | "__root__"
    | "/"
    | "/$lang"
    | "/$lang/blog"
    | "/$lang/pricing"
    | "/$lang/team"
    | "/$lang/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/$lang": {
      id: "/$lang"
      path: "/$lang"
      fullPath: "/$lang"
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/$lang/": {
      id: "/$lang/"
      path: "/"
      fullPath: "/$lang/"
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    "/$lang/team": {
      id: "/$lang/team"
      path: "/team"
      fullPath: "/$lang/team"
      preLoaderRoute: typeof LangTeamRouteImport
      parentRoute: typeof LangRouteRoute
    }
    "/$lang/pricing": {
      id: "/$lang/pricing"
      path: "/pricing"
      fullPath: "/$lang/pricing"
      preLoaderRoute: typeof LangPricingRouteImport
      parentRoute: typeof LangRouteRoute
    }
    "/$lang/blog": {
      id: "/$lang/blog"
      path: "/blog"
      fullPath: "/$lang/blog"
      preLoaderRoute: typeof LangBlogRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangBlogRoute: typeof LangBlogRoute
  LangPricingRoute: typeof LangPricingRoute
  LangTeamRoute: typeof LangTeamRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangBlogRoute: LangBlogRoute,
  LangPricingRoute: LangPricingRoute,
  LangTeamRoute: LangTeamRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
